### PR TITLE
add code for bonus 2

### PR DESCRIPTION
**Pull request by byr-gdp**
Thanks for your tutorial.

I hava read the tdd tutorial just now. When I execute bonus 2 code, nothing happened. After comparing the **change.js** in the root directory. I found the tutorial about bonus 2 missed something which would run the test.

### CODE REVIEW

**Comment by nelsonic** [comment]
@byr-gdp well spotted. thanks for the Pull Request! :+1:

**Comment by nelsonic** [comment]
@byr-gdp if you found this tutorial *useful* please :star: the repo to help others find it. thanks! :wink:

**Comment by byr-gdp** [comment]
@nelsonic Yeah! I'm a newer to Unit-Test. I want to translate this tutorial into Chinese to let more people know about it. Of course I will remain the original info. Is that OK? :smiley:

**Comment by nelsonic** [comment]
@byr-gdp go for it. if you need any help, let us know.

**Pull request merged**
